{
    "qualimap_rnaseq":
    {
        "jc": "short",
        "mem_free": "16G",
        "threads": "1",
        "local_free": "16G",
        "ramodisk": "0G"
    },
    "__default__":
    {
        "jc": "short",
        "mem_free": "8G",
        "threads": "1",
        "local_free": "1G",
        "ramdisk": "0G"
    }
}
